import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <nav style={{
           width: "100%"
          ,background: "teal"
          ,fontSize:"50px"
          ,display:"flex"
           ,justifyContent:"center"
           ,alignItems:"center"}
           }>

        <Link style={{margin:"7px"}}  href="/">home</Link>
        <Link style={{margin:"7px"}}  href="/posts">posts</Link>
       
 
        </nav>
        
        
        
        {children}</body>
    </html>
  );
}
